### ISSUE TITLE
android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub

### ISSUE THREAD

**Issue by maxveres** [afollestad/aesthetic#101]
- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Aesthetic (see the README).
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

- Affected devices: HTC One M8 (Android 6.0), HTC One M9 (Android 7.0)

As I was investigated, when 'StubView' inflating is intercepted by `InflationInterceptor`, the reason is that LayoutInflater (for `context: ContextThemeWrapper`) is created with `mConstructorArgs [0] = null`.

```kotlin
try {
        val layoutInflater = LayoutInflater.from(context) // <- Here! `name='StubView'` and context is `ContextThemeWrapper` not a `MainActivity`
        view = layoutInflater.createView(
            name,
            getViewPrefix(name),
            attrs
        )
      } catch (e: Throwable) {
        throw IllegalStateException(
            "Unable to delegate inflation of $name to normal LayoutInflater.", e
        )
      }
```

And the problem is that in all versions of android up to API 25, the context value in the `LayoutInflater.createView()` method is not correctly validated:

```java
     // ...
    
     Object[] args = mConstructorArgs;
     args[1] = attrs;

     final View view = constructor.newInstance(args);  
    
     // ...
```
From `API 26` it is correct:
```java
    Object lastContext = mConstructorArgs[0];
    if (mConstructorArgs[0] == null) {
        // Fill in the context if not already within inflation.
        mConstructorArgs[0] = mContext;
    }
    Object[] args = mConstructorArgs;
    args[1] = attrs;

    final View view = constructor.newInstance(args);
```

Stack trace:

```
09-26 02:52:43.866 4864-4864/com.afollestad.aestheticsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afollestad.aestheticsample, PID: 4864
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afollestad.aestheticsample/com.afollestad.aestheticsample.MainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2484)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
        at android.app.ActivityThread.access$900(ActivityThread.java:150)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:168)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3962)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4057)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1992)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.afollestad.aestheticsample.MainActivity.onCreate(MainActivity.kt:26)
        at android.app.Activity.performCreate(Activity.java:6248)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:168) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class ViewStub
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3962) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4057) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1992) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.afollestad.aestheticsample.MainActivity.onCreate(MainActivity.kt:26) 
        at android.app.Activity.performCreate(Activity.java:6248) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:168) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
     Caused by: java.lang.IllegalStateException: Unable to delegate inflation of ViewStub to normal LayoutInflater.
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:270)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3962) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4057) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1992) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.afollestad.aestheticsample.MainActivity.onCreate(MainActivity.kt:26) 
        at android.app.Activity.performCreate(Activity.java:6248) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:168) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class android.view.ViewStub
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:264)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3962) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4057) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1992) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.afollestad.aestheticsample.MainActivity.onCreate(MainActivity.kt:26) 
        at android.app.Activity.performCreate(Activity.java:6248) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:168) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:264) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3962) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4057) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1992) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.afollestad.aestheticsample.MainActivity.onCreate(MainActivity.kt:26) 
        at android.app.Activity.performCreate(Activity.java:6248) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:168) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
        at android.view.View.<init>(View.java:3801)
        at android.view.ViewStub.<init>(ViewStub.java:107)
        at android.view.ViewStub.<init>(ViewStub.java:103)
        at android.view.ViewStub.<init>(ViewStub.java:99)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:264) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3962) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:4057) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1992) 
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575) 
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.afollestad.aestheticsample.MainActivity.onCreate(MainActivity.kt:26) 
        at android.app.Activity.performCreate(Activity.java:6248) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1125) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2437) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544) 
        at android.app.ActivityThread.access$900(ActivityThread.java:150) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:168) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687) 
```

---

**Comment by afollestad** [comment]
Looks potentially related to https://github.com/afollestad/aesthetic/issues/92

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.7.2

**Comment by maxveres** [comment]
Good work, thanks!
