### ISSUE TITLE
Adding WebView to layout causes a ClassNotFoundException

### ISSUE THREAD

**Issue by gautam2682** [afollestad/aesthetic#108]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Aesthetic (see the README).
- [x] I have given my issue a non-generic title.
- [x] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

**If this is a feature request, you can clear everything below.**

##### Include the following:

 - Affected device(s): MiA1

```
 <WebView
            android:id="@+id/webview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
```
 
##### Reproduction Steps
Adding webview in xml leads to crash while when trying AppcompatActivity everything is working fine, also `android:tag=":aesthetic_ignore"` is not working on webview.Thank you so much.)

##### Actual Result
```xml
    Caused by: android.view.InflateException: Binary XML file line #35: Binary XML file line #35: Error inflating class WebView
     Caused by: android.view.InflateException: Binary XML file line #35: Error inflating class WebView
     Caused by: java.lang.IllegalStateException: Unable to delegate inflation of WebView to normal LayoutInflater.
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:164)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
```

**Comment by afollestad** [comment]
I've seen this further down in the stack, below the above:
```gradle
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.widget.WebView" on path: DexPathList[[zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/base.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_dependencies_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_resources_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_0_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_1_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_2_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_3_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_4_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_5_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_6_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_7_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_8_apk.apk", zip file "/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.afollestad.aestheticsample-jJUBf_QMTVWupMQugiC28Q==/lib/x86_64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:606)
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:162)
```

**Comment by afollestad** [comment]
This is very weird. 🤔

**Comment by afollestad** [comment]
Looks like it's been renamed to `android.webkit.WebView` on newer versions of Android but the `LayoutInflater` (not in Aesthetic) is trying to inflate the old version.
