### ISSUE TITLE
Error inflating class ViewStub - Context.getResources()' on a null object reference

### ISSUE THREAD

**Issue by gautam2682** [afollestad/aesthetic#113]
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [x] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/aesthetic/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have verified that I am using the latest version of Aesthetic (see the README).
- [x ] I have given my issue a non-generic title.
-  x] I have [read over the documentation](https://github.com/afollestad/aesthetic/blob/master/README.md) (before asking questions on how to do something).

---

**If this is a feature request, you can clear everything below.**

##### Include the following:

 - Affected device(s): Oppo RMX1805 Android 8.1.0 and many vivo devices

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.MainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2949)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
 
```
There are also some bugs in library which is specific to particular device , i could not get crash reports but crash free users decreased  .The app is not opening on some devices therefore i have to roll back the updates , please check this . And thanks , i think you are lifetimes ahead of many developers .

**Comment by afollestad** [comment]
Could you post more of the crash log below what's above?

**Comment by gautam2682** [comment]
#0. Crashed: main
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2949)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

--

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.MainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2949)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

Caused by android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub


Caused by android.view.InflateException: Binary XML file line #29: Error inflating class ViewStub


Caused by java.lang.IllegalStateException: Unable to delegate inflation of ViewStub to normal LayoutInflater.
       at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(Unknown Source:236)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:779)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:831)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2143)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2736)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2842)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2133)
       at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(Unknown Source:82)
       at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:4)
       at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(Unknown Source)
       at androidx.appcompat.app.AppCompatActivity.setContentView(Unknown Source:4)
       at com.MainActivity.onCreate(Unknown Source:9)
       at android.app.Activity.performCreate(Activity.java:7263)
       at android.app.Activity.performCreate(Activity.java:7254)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2902)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

Caused by android.view.InflateException: Binary XML file line #29: Error inflating class android.view.ViewStub


Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:650)
       at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(Unknown Source:206)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:779)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:831)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2143)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2736)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2842)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2133)
       at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(Unknown Source:82)
       at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:4)
       at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(Unknown Source)
       at androidx.appcompat.app.AppCompatActivity.setContentView(Unknown Source:4)
       at com.MainActivity.onCreate(Unknown Source:9)
       at android.app.Activity.performCreate(Activity.java:7263)
       at android.app.Activity.performCreate(Activity.java:7254)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2902)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.view.ViewConfiguration.get(ViewConfiguration.java:432)
       at android.view.View.(View.java:4635)
       at android.view.ViewStub.(ViewStub.java:107)
       at android.view.ViewStub.(ViewStub.java:103)
       at android.view.ViewStub.(ViewStub.java:99)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
       at android.view.LayoutInflater.createView(LayoutInflater.java:650)
       at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(Unknown Source:206)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:779)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:831)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
       at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2143)
       at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2736)
       at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2842)
       at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2133)
       at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(Unknown Source:82)
       at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(Unknown Source:4)
       at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(Unknown Source)
       at androidx.appcompat.app.AppCompatActivity.setContentView(Unknown Source:4)
       at com.MainActivity.onCreate(Unknown Source:9)
       at android.app.Activity.performCreate(Activity.java:7263)
       at android.app.Activity.performCreate(Activity.java:7254)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2902)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

#0. Crashed: main
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2949)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3027)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1745)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:183)
       at android.app.ActivityThread.main(ActivityThread.java:6956)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:519)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

#1. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#2. FinalizerWatchdogDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:302)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:282)
       at java.lang.Daemons$Daemon.run(Daemons.java:108)
       at java.lang.Thread.run(Thread.java:764)

#3. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#4. Crashlytics Exception Handler1
       at dalvik.system.VMStack.getThreadStackTrace(VMStack.java)
       at java.lang.Thread.getStackTrace(Thread.java:1538)
       at java.lang.Thread.getAllStackTraces(Thread.java:1588)
       at com.crashlytics.android.core.CrashlyticsController.enableExceptionHandling(Unknown Source:102)
       at com.crashlytics.android.core.CrashlyticsController.enableExceptionHandling(Unknown Source:78)
       at com.crashlytics.android.core.CrashlyticsController.enableExceptionHandling(Unknown Source)
       at com.crashlytics.android.core.CrashlyticsController$7.call(Unknown Source:17)
       at com.crashlytics.android.core.CrashlyticsController$7.call(Unknown Source)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(Unknown Source:2)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(Unknown Source:5)
       at java.lang.Thread.run(Thread.java:764)

#5. queued-work-looper
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:155)
       at android.os.HandlerThread.run(HandlerThread.java:65)

#6. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#7. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#8. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#9. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#10. ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:183)
       at java.lang.Daemons$Daemon.run(Daemons.java:108)
       at java.lang.Thread.run(Thread.java:764)

#11. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#12. OkHttp ConnectionPool
       at java.lang.Object.wait(Object.java)
       at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:103)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#13. main
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
       at java.util.concurrent.FutureTask.get(FutureTask.java:205)
       at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(Unknown Source:21)
       at com.crashlytics.android.core.CrashlyticsController.enableExceptionHandling(Unknown Source:62)
       at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(Unknown Source:2)
       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(Unknown Source:13)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
       at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

#14. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#15. RxSchedulerPurge-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#16. Queue
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:548)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:24)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.peek(Unknown Source)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source:2)
       at io.fabric.sdk.android.services.concurrency.DependencyPriorityBlockingQueue.take(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#17. RxCachedWorkerPoolEvictor-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#18. pool-1-thread-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

#19. TcmReceiver
       at android.net.LocalSocketImpl.readba_native(LocalSocketImpl.java)
       at android.net.LocalSocketImpl.-wrap1(Unknown Source)
       at android.net.LocalSocketImpl$SocketInputStream.read(LocalSocketImpl.java:110)
       at com.qti.tcmclient.DpmTcmClient$TcmReceiver.run(DpmTcmClient.java:143)
       at java.lang.Thread.run(Thread.java:764)

#20. Answers Events Handler1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2137)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(Unknown Source:2)
       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(Unknown Source:5)
       at java.lang.Thread.run(Thread.java:764)

#21. FinalizerDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:422)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
       at java.lang.Daemons$Daemon.run(Daemons.java:108)
       at java.lang.Thread.run(Thread.java:764)

**Comment by afollestad** [comment]
@gautam2682 hmm, are you sure you're using the latest version of this library? This was fixed

**Comment by gautam2682** [comment]
yes sir, i am sure i released this update only after adding beta03 version of this library.

**Comment by DeweyReed** [comment]
Actually we can return `null` in the `InflationInterceptor.onCreateView` instead of throwing an exception because `Factory2` says
```
         * @return View Newly created view. Return null for the default
         *         behavior.
```
But in this way, we can't tint this view.

**Comment by afollestad** [comment]
Yes, there is more to be done after view construction.
