### ISSUE TITLE
Another Error inflating class ViewStub - Context.getResources()' on a null object reference

### ISSUE THREAD

**Issue by ItsCalebJones** [afollestad/aesthetic#140]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

1.0.0-beta05
 
**Affected Device(s):**
 
Oppo realme 1 - Android v9
 
**Describe the Bug:**

Application crashes during view inflation.

**Expected Behavior:**

Application should not crash at view inflation.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{me.calebjones.spacelaunchnow/me.calebjones.spacelaunchnow.ui.main.MainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub
       at android.app.ActivityThread.performLaunchActivity + 3175(ActivityThread.java:3175)
       at android.app.ActivityThread.handleLaunchActivity + 3312(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 113(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute + 71(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage + 2038(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 226(Looper.java:226)
       at android.app.ActivityThread.main + 7172(ActivityThread.java:7172)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 576(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main + 942(ZygoteInit.java:942)
```
```
Caused by android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class ViewStub
```
```
Caused by android.view.InflateException: Binary XML file line #29: Error inflating class ViewStub

```
```
Caused by java.lang.IllegalStateException: Unable to delegate inflation of ViewStub to normal LayoutInflater.
       at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView + 171(SourceFile:171)
       at android.view.LayoutInflater.createViewFromTag + 784(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag + 740(LayoutInflater.java:740)
       at android.view.LayoutInflater.rInflate + 890(LayoutInflater.java:890)
       at android.view.LayoutInflater.rInflateChildren + 851(LayoutInflater.java:851)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate + 374(LayoutInflater.java:374)
       at com.android.internal.policy.DecorView.onResourcesLoaded + 2208(DecorView.java:2208)
       at com.android.internal.policy.PhoneWindow.generateLayout + 2770(PhoneWindow.java:2770)
       at com.android.internal.policy.PhoneWindow.installDecor + 2877(PhoneWindow.java:2877)
       at com.android.internal.policy.PhoneWindow.getDecorView + 2142(PhoneWindow.java:2142)
       at androidx.appcompat.app.AppCompatDelegateImpl.k + 576(SourceFile:576)
       at androidx.appcompat.app.AppCompatDelegateImpl.j + 519(SourceFile:519)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView + 467(SourceFile:467)
       at androidx.appcompat.app.AppCompatActivity.setContentView + 141(SourceFile:141)
       at me.calebjones.spacelaunchnow.ui.main.MainActivity.onCreate + 176(SourceFile:176)
       at android.app.Activity.performCreate + 7376(Activity.java:7376)
       at android.app.Activity.performCreate + 7367(Activity.java:7367)
       at android.app.Instrumentation.callActivityOnCreate + 1271(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity + 3155(ActivityThread.java:3155)
       at android.app.ActivityThread.handleLaunchActivity + 3312(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 113(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute + 71(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage + 2038(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 226(Looper.java:226)
       at android.app.ActivityThread.main + 7172(ActivityThread.java:7172)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 576(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main + 942(ZygoteInit.java:942)
```
```
Caused by android.view.InflateException: Binary XML file line #29: Error inflating class android.view.ViewStub
```
```
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance + 343(Constructor.java:343)
       at android.view.LayoutInflater.createView + 652(LayoutInflater.java:652)
       at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView + 169(SourceFile:169)
       at android.view.LayoutInflater.createViewFromTag + 784(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag + 740(LayoutInflater.java:740)
       at android.view.LayoutInflater.rInflate + 890(LayoutInflater.java:890)
       at android.view.LayoutInflater.rInflateChildren + 851(LayoutInflater.java:851)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate + 374(LayoutInflater.java:374)
       at com.android.internal.policy.DecorView.onResourcesLoaded + 2208(DecorView.java:2208)
       at com.android.internal.policy.PhoneWindow.generateLayout + 2770(PhoneWindow.java:2770)
       at com.android.internal.policy.PhoneWindow.installDecor + 2877(PhoneWindow.java:2877)
       at com.android.internal.policy.PhoneWindow.getDecorView + 2142(PhoneWindow.java:2142)
       at androidx.appcompat.app.AppCompatDelegateImpl.k + 576(SourceFile:576)
       at androidx.appcompat.app.AppCompatDelegateImpl.j + 519(SourceFile:519)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView + 467(SourceFile:467)
       at androidx.appcompat.app.AppCompatActivity.setContentView + 141(SourceFile:141)
       at me.calebjones.spacelaunchnow.ui.main.MainActivity.onCreate + 176(SourceFile:176)
       at android.app.Activity.performCreate + 7376(Activity.java:7376)
       at android.app.Activity.performCreate + 7367(Activity.java:7367)
       at android.app.Instrumentation.callActivityOnCreate + 1271(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity + 3155(ActivityThread.java:3155)
       at android.app.ActivityThread.handleLaunchActivity + 3312(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 113(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute + 71(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage + 2038(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 226(Looper.java:226)
       at android.app.ActivityThread.main + 7172(ActivityThread.java:7172)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 576(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main + 942(ZygoteInit.java:942)
```
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
       at android.view.ViewConfiguration.get + 447(ViewConfiguration.java:447)
       at android.view.View.<init> + 4865(View.java:4865)
       at android.view.ViewStub.<init> + 107(ViewStub.java:107)
       at android.view.ViewStub.<init> + 103(ViewStub.java:103)
       at android.view.ViewStub.<init> + 99(ViewStub.java:99)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance + 343(Constructor.java:343)
       at android.view.LayoutInflater.createView + 652(LayoutInflater.java:652)
       at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView + 169(SourceFile:169)
       at android.view.LayoutInflater.createViewFromTag + 784(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag + 740(LayoutInflater.java:740)
       at android.view.LayoutInflater.rInflate + 890(LayoutInflater.java:890)
       at android.view.LayoutInflater.rInflateChildren + 851(LayoutInflater.java:851)
       at android.view.LayoutInflater.inflate + 515(LayoutInflater.java:515)
       at android.view.LayoutInflater.inflate + 423(LayoutInflater.java:423)
       at android.view.LayoutInflater.inflate + 374(LayoutInflater.java:374)
       at com.android.internal.policy.DecorView.onResourcesLoaded + 2208(DecorView.java:2208)
       at com.android.internal.policy.PhoneWindow.generateLayout + 2770(PhoneWindow.java:2770)
       at com.android.internal.policy.PhoneWindow.installDecor + 2877(PhoneWindow.java:2877)
       at com.android.internal.policy.PhoneWindow.getDecorView + 2142(PhoneWindow.java:2142)
       at androidx.appcompat.app.AppCompatDelegateImpl.k + 576(SourceFile:576)
       at androidx.appcompat.app.AppCompatDelegateImpl.j + 519(SourceFile:519)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView + 467(SourceFile:467)
       at androidx.appcompat.app.AppCompatActivity.setContentView + 141(SourceFile:141)
       at me.calebjones.spacelaunchnow.ui.main.MainActivity.onCreate + 176(SourceFile:176)
       at android.app.Activity.performCreate + 7376(Activity.java:7376)
       at android.app.Activity.performCreate + 7367(Activity.java:7367)
       at android.app.Instrumentation.callActivityOnCreate + 1271(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity + 3155(ActivityThread.java:3155)
       at android.app.ActivityThread.handleLaunchActivity + 3312(ActivityThread.java:3312)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 113(TransactionExecutor.java:113)
       at android.app.servertransaction.TransactionExecutor.execute + 71(TransactionExecutor.java:71)
       at android.app.ActivityThread$H.handleMessage + 2038(ActivityThread.java:2038)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 226(Looper.java:226)
       at android.app.ActivityThread.main + 7172(ActivityThread.java:7172)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 576(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main + 942(ZygoteInit.java:942)
```

**Comment by hedongfu** [comment]
I have same issue. This issue is permanente on Oppo Reno or Realme phone. It seems two libraries are missing from Oppo phone, MultiDexApplication and CoreComponentFactory. If you roll back from Android X to previous Google support library. These issues may gone.
I don't have a better solution now.

java.lang.RuntimeException: Unable to instantiate application androidx.multidex.MultiDexApplication: java.lang.ClassNotFoundException: Didn't find class "androidx.multidex.MultiDexApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1130)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6245)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1835)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7182)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.multidex.MultiDexApplication" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", 
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6245) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1835) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7182) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)

**Comment by hedongfu** [comment]
The problem is Oppo phone doesn't support Android X. I create a very simple Android project which using Android X. It crashes repeatedly on my Realme Phone.
Maybe the only way to resolve this issue is revert from Android X to previous Android support library.

**Comment by hedongfu** [comment]
I rollback both my app and aesthetic from AndroidX to AppCompact, it's still crash on Realme phone. I tried aesthetic sample with 0.6.1 version, same result.
So, this crash is somehow related with aesthetic or its libraries.
