### ISSUE TITLE
NullPointerException in Aesthetic#subscribeBackgroundListeners

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#18]
Device: any
Android version: same result on 7.0+

```gradle
java.lang.RuntimeException: Unable to resume activity {com.mnml.music.test/com.mnml.music.ui.activity.AboutActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3644)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3684)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2896)
                                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                       at android.os.Looper.loop(Looper.java:164)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6535)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                       at com.afollestad.aesthetic.Aesthetic.subscribeBackgroundListeners(Aesthetic.java:258)
                                                                       at com.afollestad.aesthetic.Aesthetic.resume(Aesthetic.java:169)
                                                                       at com.afollestad.aesthetic.AestheticActivity.onResume(AestheticActivity.java:19)
                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                                                                       at android.app.Activity.performResume(Activity.java:7058)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3619)
```

Source code at https://github.com/MnmlOS/Music

Appears to be an issue relating to AboutLibraries

**Comment by afollestad** [comment]
Fixed in 0.4.1
