### ISSUE TITLE
Null pointer in AestheticViewPager when resolving accent color

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#19]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

 - Aesthetic version: `0.4.1`
 - Device OS version: `7.1.2+`
 - Device: Any
Source code at https://github.com/MnmlOS/Music
```gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
                                                       at com.afollestad.aesthetic.Util.resolveColor(Util.java:85)
                                                       at com.afollestad.aesthetic.Util.resolveColor(Util.java:80)
                                                       at com.afollestad.aesthetic.Aesthetic.colorAccent(Aesthetic.java:383)
                                                       at com.afollestad.aesthetic.AestheticViewPager.onAttachedToWindow(AestheticViewPager.java:35)
                                                       at android.view.View.dispatchAttachedToWindow(View.java:15513)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:887)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:699)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:634)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:873)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```
 
###### Reproduction Steps
Run app for the first time

###### Expected Result
Successful launch

###### Actual Result
Crash

**Comment by afollestad** [comment]
Hmm, well that doesn't occur in the sample project so there may be something wrong with your configuration.

**Comment by boswelja** [comment]
I thought I may have been calling the first time init too late, but according to the readme, that shouldnt be the case

**Comment by afollestad** [comment]
Well, this would generally happen if the the view pager were trying to access the current accent color after the Activity it's contained in is paused, but that shouldn't really happen 🤔

**Comment by boswelja** [comment]
The crash occurs around the point when the permission dialog appears, but the viewpager shouldnt even be configured by then?

**Comment by afollestad** [comment]
All views in Aesthetic subscribe to theme color changes when they attach to their Activity 😁 https://github.com/afollestad/aesthetic/blob/master/library/src/main/java/com/afollestad/aesthetic/AestheticViewPager.java#L33

And because of that, the Activity definitely should not be null. So this is very weird.

**Comment by boswelja** [comment]
Oh, I think I see the problem now.
When the permission dialog appears (Which must be around the same time the viewpager get the accent color) the activity is paused until the user responds
I'll move the permission request further back and see what happens :)

**Comment by afollestad** [comment]
Ohhhhh, yeah, you're right. I can actually make a workaround for that 😀

**Comment by boswelja** [comment]
Ooh, sounds good :D

**Comment by afollestad** [comment]
Alright, so 0.4.2 should fix the problem by only clearing the context in Aesthetic if the active Activity is finishing (not just pausing to come back later) 😁

**Comment by boswelja** [comment]
Yay, I'll test it now :D

**Comment by boswelja** [comment]
So this issue is fixed, there are still more crashes *after* the  permission dialog, I'll have to work that one out later as I'm out of time
