### ISSUE TITLE
NullPointerException in AestheticToolbar

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#21]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.3`
 - Device OS version: `7.1.2+`
 - Device: Any

```gradle
io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
                                                                         at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
                                                                         at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
                                                                         at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                         at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                                       ComposedException 1 :
                                                                     	java.lang.NullPointerException: Attempt to invoke virtual method 'void io.reactivex.subjects.PublishSubject.onNext(java.lang.Object)' on a null object reference
                                                                         at com.afollestad.aesthetic.AestheticToolbar.invalidateColors(AestheticToolbar.java:54)
                                                                         at com.afollestad.aesthetic.AestheticToolbar.access$000(AestheticToolbar.java:21)
                                                                         at com.afollestad.aesthetic.AestheticToolbar$1.accept(AestheticToolbar.java:93)
                                                                         at com.afollestad.aesthetic.AestheticToolbar$1.accept(AestheticToolbar.java:90)
                                                                         at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
                                                                         at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                                         at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                         at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6244)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```
 
###### Reproduction Steps
Launch app for first time or after clearing data

###### Expected Result
Successful launch

###### Actual Result
Crash

**Comment by afollestad** [comment]
Fixed in https://github.com/afollestad/aesthetic/releases/tag/0.4.4

**Comment by boswelja** [comment]
Good news! My app is launching successfully now :D
