### ISSUE TITLE
?cardBackgroundColor causing crash

### ISSUE THREAD

**Issue by hugocastelani** [afollestad/aesthetic#28]
`?cardBackgroundColor` is available, but apparently doesn't return a valid value, and as result, InflateException is thrown.

```gradle
05-23 17:02:05.397 E/AndroidRuntime(16675): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.CardView
05-23 17:02:05.397 E/AndroidRuntime(16675): Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0100f1 a=-1}
05-23 17:02:05.397 E/AndroidRuntime(16675): 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
05-23 17:02:05.397 E/AndroidRuntime(16675): 	at android.support.v7.widget.CardView.initialize(CardView.java:220)
05-23 17:02:05.397 E/AndroidRuntime(16675): 	at android.support.v7.widget.CardView.<init>(CardView.java:116)
05-23 17:02:05.397 E/AndroidRuntime(16675): 	at com.afollestad.aesthetic.AestheticCardView.<init>(AestheticCardView.java:27)
05-23 17:02:05.397 E/AndroidRuntime(16675): 	at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.java:205)
```

<h3>Edit:</h3>

There are several crashes which are the result of `app:cardBackgroundColor="?cardBackgroundColor"`. I can guarantee that all situations work properly without this single line.

<h6>Device information:</h6>

- Device OS version: 7.1.0
- Device Manufacturer: Google
- Device Name: Nexus 5X

<h3>Situation one:</h3>

<h6>Project information:</h6>

- Aesthetic version: 0.4.6
- XML class: `com.afollestad.aesthetic.AestheticCardView`

<h6>Crash:</h6>

``` gradle
05-24 09:27:08.712 15759-15759/com.hcastelani.buster E/AndroidRuntime: FATAL EXCEPTION: main
	   Process: com.hcastelani.buster, PID: 15759
	   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hcastelani.buster/com.hcastelani.buster.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class <unknown>
		Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class <unknown>
		Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class <unknown>
		Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0100d2 a=-1}
		   at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
		   at android.support.v7.widget.CardView.initialize(CardView.java:220)
		   at android.support.v7.widget.CardView.<init>(CardView.java:116)
		   at com.afollestad.aesthetic.AestheticCardView.<init>(AestheticCardView.java:27)
```

[Whole logcat (situation one)](https://github.com/afollestad/aesthetic/files/1025725/Situation.one.txt)

<h3>Situation two:</h3>

<h6>Project information:</h6>

- Aesthetic version: 0.4.6
- XML class: `android.support.v7.widget.CardView`

<h6>Crash:</h6>

``` gradle
05-24 09:42:35.438 16775-16775/com.hcastelani.buster E/AndroidRuntime: FATAL EXCEPTION: main
	   Process: com.hcastelani.buster, PID: 16775
	   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hcastelani.buster/com.hcastelani.buster.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class android.support.v7.widget.CardView
		Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class android.support.v7.widget.CardView
		Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.v7.widget.CardView
		Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0100d2 a=-1}
		   at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
		   at android.support.v7.widget.CardView.initialize(CardView.java:220)
		   at android.support.v7.widget.CardView.<init>(CardView.java:116)
		   at com.afollestad.aesthetic.AestheticCardView.<init>(AestheticCardView.java:27)
		   at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.java:205)
```
[Whole logcat (situation two)](https://github.com/afollestad/aesthetic/files/1025728/Situation.two.txt)

<h3>Situation three:</h3>

<h6>Project information:</h6>

- Aesthetic version: 0.4.7
- XML class: `com.afollestad.aesthetic.AestheticCardView`

<h6>Crash:</h6>

``` gradle
8:41.864 17709-17709/com.hcastelani.buster E/AndroidRuntime: FATAL EXCEPTION: main
	   Process: com.hcastelani.buster, PID: 17709
	   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hcastelani.buster/com.hcastelani.buster.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class <unknown>
		Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class <unknown>
		Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class <unknown>
		Caused by: java.lang.reflect.InvocationTargetException
		Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0100d2 a=-1}
		   at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
		   at android.support.v7.widget.CardView.initialize(CardView.java:220)
		   at android.support.v7.widget.CardView.<init>(CardView.java:116)
		   at com.afollestad.aesthetic.AestheticCardView.<init>(AestheticCardView.java:27)
```
[Whole logcat (situation three)](https://github.com/afollestad/aesthetic/files/1025731/Situation.three.txt)

<h3>Situation four:</h3>

<h6>Project information:</h6>

- Aesthetic version: 0.4.7
- XML class: `android.support.v7.widget.CardView`

<h6>Crash:</h6>

``` gradle
05-24 09:54:54.236 19122-19122/? E/AndroidRuntime: FATAL EXCEPTION: main
	   Process: com.hcastelani.buster, PID: 19122
	   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hcastelani.buster/com.hcastelani.buster.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class android.support.v7.widget.CardView
		Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class android.support.v7.widget.CardView
		Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class android.support.v7.widget.CardView
		Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f0100d2 a=-1}
		   at android.content.res.TypedArray.getColorStateList(TypedArray.java:528)
		   at android.support.v7.widget.CardView.initialize(CardView.java:220)
		   at android.support.v7.widget.CardView.<init>(CardView.java:116)
		   at com.afollestad.aesthetic.AestheticCardView.<init>(AestheticCardView.java:27)
		   at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.java:205))
```
[Whole logcat (situation four)](https://github.com/afollestad/aesthetic/files/1025753/Situation.four.txt)

Seems these crashes happens in any condition, therefore, there's no need to leave my code here.

**Comment by afollestad** [comment]
Hmm, that shouldn't happen unless your themes are overriding it.

The default values for that attribute are plain color resources which are fully supported (http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/frameworks/support/v7/cardview/res/values/colors.xml/).

**Comment by HugoCastelani** [comment]
That's weird... I'm using just an ordinary theme without any customization.

**Comment by HugoCastelani** [comment]
I'll leave my code as soon as I can.

**Comment by timusus** [comment]
@HugoCastelani can you also provide the following (preferably just edit your first comment)

###### Include the following:
 - Aesthetic version: `0.x.x.x`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, some steps to reproduce the issue would be super helpful.

**Comment by HugoCastelani** [comment]
@timusus Done. Thank you.
@afollestad Perhaps the new informations are useful.

**Comment by boswelja** [comment]
Maybe aesthetic is storing it's own version somewhere?

**Comment by timusus** [comment]
@HugoCastelani are you setting the `isDark()` property when setting up `Aesthetic`?

For example:
```
Aesthetic.get()
    ...
    .isDark(true)
    ...
```

Just curious, as I did experience a crash with Aesthetic and the card's background, when I forgot to set this property, and I was using a dark theme.

**Comment by aminecmi** [comment]
@timusus so you only can change the card background with the dark theme on ?

**Comment by timusus** [comment]
@aminecmi no, but if you are using a dark theme, and you don't set `isDark(true)` you _may_ experience a crash, as the `Aesthetic` `Observable` emits `-1` for an `@ColorResId` value (or something along those lines).

**Comment by aminecmi** [comment]
I don't think this is related to the library.
I removed it from my app, and I still had the problem when trying to use ```cardBackgroundColor``` on some elements.

**Comment by HugoCastelani** [comment]
@timusus Sorry the delay.
Actually, the intention was using this with or without dark theme because aesthetic is quite slow with setting card's background. In a RecyclerView for example, it's explicit the color change.
In my case, I set a dark color as `cardBackgroundColor` if `isDark()` returns true, so it can't be the reason.

**Comment by afollestad** [comment]
I don't believe this is related to this library. It's more of an Android framework issue.
