### ISSUE TITLE
Crash when using adaptive icons

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#37]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `8.0.0`
 - Device Manufacturer: `Google`
 - Device Name: `Nexus 5X`

```gradle
06-09 18:18:59.997 1567-1567/com.mnml.music.test W/System.err: java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
06-09 18:18:59.998 1567-1567/com.mnml.music.test W/System.err:     at com.afollestad.aesthetic.Util.setTaskDescriptionColor(Util.java:260)
06-09 18:18:59.998 1567-1567/com.mnml.music.test W/System.err:     at com.afollestad.aesthetic.Aesthetic$1.accept(Aesthetic.java:194)
06-09 18:18:59.999 1567-1567/com.mnml.music.test W/System.err:     at com.afollestad.aesthetic.Aesthetic$1.accept(Aesthetic.java:191)
06-09 18:18:59.999 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
06-09 18:18:59.999 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
06-09 18:19:00.000 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
06-09 18:19:00.000 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
06-09 18:19:00.000 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
06-09 18:19:00.001 1567-1567/com.mnml.music.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:769)
06-09 18:19:00.001 1567-1567/com.mnml.music.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
06-09 18:19:00.002 1567-1567/com.mnml.music.test W/System.err:     at android.os.Looper.loop(Looper.java:164)
06-09 18:19:00.002 1567-1567/com.mnml.music.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
06-09 18:19:00.002 1567-1567/com.mnml.music.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-09 18:19:00.003 1567-1567/com.mnml.music.test W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-09 18:19:00.003 1567-1567/com.mnml.music.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
06-09 18:19:00.092 1567-1567/com.mnml.music.test W/System.err: io.reactivex.exceptions.CompositeException: 1 exceptions occurred. 
06-09 18:19:00.092 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
06-09 18:19:00.092 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:64)
06-09 18:19:00.092 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
06-09 18:19:00.092 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:769)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at android.os.Looper.loop(Looper.java:164)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
06-09 18:19:00.093 1567-1567/com.mnml.music.test W/System.err:   ComposedException 1 :
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err: 	java.lang.ClassCastException: android.graphics.drawable.AdaptiveIconDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at com.afollestad.aesthetic.Util.setTaskDescriptionColor(Util.java:260)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at com.afollestad.aesthetic.Aesthetic$1.accept(Aesthetic.java:194)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at com.afollestad.aesthetic.Aesthetic$1.accept(Aesthetic.java:191)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at android.os.Handler.handleCallback(Handler.java:769)
06-09 18:19:00.094 1567-1567/com.mnml.music.test W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
06-09 18:19:00.095 1567-1567/com.mnml.music.test W/System.err:     at android.os.Looper.loop(Looper.java:164)
06-09 18:19:00.095 1567-1567/com.mnml.music.test W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
06-09 18:19:00.095 1567-1567/com.mnml.music.test W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-09 18:19:00.095 1567-1567/com.mnml.music.test W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-09 18:19:00.095 1567-1567/com.mnml.music.test W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
 
###### Reproduction Steps
Launch app with adaptive icons enabled

###### Expected Result
Successful launch, adaptive icons working

###### Actual Result
App crashes, adaptive icons aren't affected

**Comment by afollestad** [comment]
Will close once I push a newer release

**Comment by boswelja** [comment]
When do you plan on pushing a new release?

**Comment by afollestad** [comment]
Not releasing quite yet but closing this issue

**Comment by mmoczkowski** [comment]
So, any plans to fix it?

**Comment by boswelja** [comment]
@mmoczkowski see above it is fixed, just waiting for a new release

**Comment by crutchcorn** [comment]
It would be awesome to push a new release with this fix. I know this is depreciated, but a final release would be nice

**Comment by afollestad** [comment]
@crutchcorn it's not deprecated actually, just kinda on hold since I started a new job in a different state 3-4 months ago 😉

**Comment by crutchcorn** [comment]
Oh! I'm so sorry, I thought I had saw a comment in the README about it being depreciated - must've been one of the other libs in a project I was looking at. 😅😅😅Did NOT mean to be *that guy*.

**Comment by afollestad** [comment]
Haha! No worries. I'll see what I can do later today.

**Comment by afollestad** [comment]
As a first step, the whole project has been converted to Kotlin and cleaned up a bit.

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.5.0 CC @crutchcorn
