### ISSUE TITLE
java.lang.NoSuchMethodError: No static method lambda$distinctToMainThread; in class com/afollestad/aesthetic/Rx

### ISSUE THREAD

**Issue by boswelja** [afollestad/aesthetic#4]
```gradle
05-14 15:48:15.440 3251-3251/com.mnml.music.test E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.mnml.music.test, PID: 3251
java.lang.NoSuchMethodError: No static method lambda$distinctToMainThread$1(Lrx/Observable;)Lrx/Observable; in class Lcom/afollestad/aesthetic/Rx; or its super classes (declaration of 'com.afollestad.aesthetic.Rx' appears in /data/app/com.mnml.music.test-2/base.apk)
                                                                       at com.afollestad.aesthetic.Rx$$Lambda$2.call(Unknown Source)
                                                                       at rx.Observable.compose(Observable.java:278)
                                                                       at com.afollestad.aesthetic.Aesthetic.resume(Aesthetic.java:134)
                                                                       at com.afollestad.aesthetic.AestheticActivity.onResume(AestheticActivity.java:19)
                                                                       at com.mnml.music.ui.activity.MainActivity.onResume(MainActivity.java:548)
                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
                                                                       at android.app.Activity.performResume(Activity.java:6824)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3421)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3484)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2747)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

Source code is at https://github.com/MnmlOS/Music on branch 'aesthetic'

**Comment by afollestad** [comment]
Hmm. That looks like a Proguard issue.

**Comment by boswelja** [comment]
Thats what I thought, but I have proguard disabled on debug builds

**Comment by boswelja** [comment]
I'll add RXJava and aesthetic rules to my proguard and see what happens anyways

**Comment by boswelja** [comment]
I updated my apps Proguard file, it's still giving the same error

**Comment by boswelja** [comment]
@afollestad Changing my proguard did nothing to help

**Comment by jahirfiquitiva** [comment]
I'm facing the exact same issue. Any suggestions to fix it?

**Comment by jahirfiquitiva** [comment]
I'm facing the exact same issue. Any suggestions to fix it?

**Comment by afollestad** [comment]
That's weird. I'm not sure what would cause it.

**Comment by wakim** [comment]
Just suggesting, but to me it looks like a dex count issue. Do you know if the app already reached 65k dex limit? Can you check using this plugin: https://github.com/KeepSafe/dexcount-gradle-plugin?

**Comment by jahirfiquitiva** [comment]
@wakim I don't think that's the reason. I'm testing this in a clean new project.

**Comment by afollestad** [comment]
Weird that it would work in the sample but not through the dependency. That class definitely exists.

**Comment by boswelja** [comment]
I'll try building the module and including the aar later and see what happens

**Comment by afollestad** [comment]
Are you by chance using a newer or older version of the Support library? (not 25.0.3?)

**Comment by boswelja** [comment]
Support library is up-to-date on my end

**Comment by jahirfiquitiva** [comment]
Support library is updated here too.

**Comment by boswelja** [comment]
After building from source and including the aar, I was unable to build my app due to a bunch of warnings about missing rx.* classes

**Comment by boswelja** [comment]
EDIT: This happens if your app has Proguard enabled regardless

**Comment by boswelja** [comment]
@afollestad I noticed your RXJava plugin is out of date, is there a reason for that?

**Comment by afollestad** [comment]
@boswelja I'm using the most recent version of Rx 1, I don't want to migrate to Rx 2 right now.

**Comment by afollestad** [comment]
@boswelja can you try adding [Retrolambda](https://github.com/evant/gradle-retrolambda) to your app (and set compile options to use Java 8)?

**Comment by boswelja** [comment]
I can try when I get home (about 2 hours)

**Comment by boswelja** [comment]
So I can't seem to get RetroLambda to work :/ Keeps giving errors about missing retroLambda method on Gradle build

**Comment by boswelja** [comment]
@jahirfiquitiva by any chance, are you using gradle plugin 2.4.0-alpha7

**Comment by boswelja** [comment]
@afollestad could that be the issue? Gradle 2.4 has native java8 support, whereas the library relies on Retrolambda

**Comment by jahirfiquitiva** [comment]
@boswelja 
I'm using Gradle Plugin 2.3.2, and not using retrolambda nor any Rx library as they are not explicitely said they're needed in aesthetic's documentation.
To use Java 8 in my library project, I'm using what is [explained here](http://stackoverflow.com/a/38360596/4864104), basically.
All my own methods and code using lambdas and stuff work without any issue. But implementing aesthetic causes this crash on start.

Btw, I haven't tried `0.0.6` nor the new `0.2.0` versions, and I don't think I'm going to be able to try them anytime soon (maybe until the weekend).

**Comment by boswelja** [comment]
Hmmm, I suspect it's the fact we are using different lambda expressions

**Comment by boswelja** [comment]
@afollestad @jahirfiquitiva I solved it :D
I had to remove retrolambda and use gradle 2.4.0-alpha7 for lambdas, right now it seems I need to include RXJava, RXAndroid, and RXPrefs dependencies in my project

**Comment by afollestad** [comment]
In release 0.3.0, I've removed all lamdas from the code base. There should no longer be any clash issues.

**Comment by nikolasamardzija** [comment]
Is there a way to fix this issue without removing all lambdas?  @afollestad
