### ISSUE TITLE
NPE on demo app

### ISSUE THREAD

**Issue by MarcinOrlowski** [afollestad/aesthetic#42]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
	at com.afollestad.aesthetic.Util.resolveColor(Util.java:85)
	at com.afollestad.aesthetic.Util.resolveColor(Util.java:80)
	at com.afollestad.aesthetic.Aesthetic.colorPrimary(Aesthetic.java:358)
	at com.afollestad.aesthetic.AestheticToolbar.onAttachedToWindow(AestheticToolbar.java:84)
	at android.view.View.dispatchAttachedToWindow(View.java:14577)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2844)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2851)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2851)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2851)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2851)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2851)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2851)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1366)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1109)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6046)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:152)
	at android.app.ActivityThread.main(ActivityThread.java:5507)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)


```

**Comment by boswelja** [comment]
I guess the sample hasn't been updated in awhile.. Line 85 in Util is blank

**Comment by timusus** [comment]
@MarcinOrlowski

Can you edit your report and include the following:

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Aesthetic (see the README)
- [ ] I have given my issue description title
- [ ] I have read over the documentation (before asking questions on how to do something).

 - Aesthetic version: `0.x.x.x`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

**Comment by timusus** [comment]
@MarcinOrlowski 

Can you edit your issue report and include the following:

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Aesthetic (see the README)
- [ ] I have given my issue description title
- [ ] I have read over the documentation (before asking questions on how to do something).

 - Aesthetic version: `0.x.x.x`
 - Device OS version: `7.1.2`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

**Comment by afollestad** [comment]
Well, you're using Xposed on your device so I'd be surprised if it wasn't related.

**Comment by MarcinOrlowski** [comment]
Maybe. But the Xposed is not causing any troubles on daily use here though...

**Comment by boswelja** [comment]
Xposed would explain why this occurs. I am unable to reproduce this error on my Nexus 5X running O DP3

**Comment by afollestad** [comment]
This would happen if `getContext()` returned null in a `View` *after* `onAttachedToWindow()` is called which is basically impossible.
