### ISSUE TITLE
Exception with MaterialDialogs support, and AestheticBottomNavigationView support

### ISSUE THREAD

**Issue by HIjack2015** [afollestad/aesthetic#49]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `4.1 and  6.0`
 - Device Manufacturer: `Google`
 - Device Name: `nexus_5x`

i  download the sample and  change the launch activity to  BottomNavActivity.then i  modify it like this
```java
 @Override
  protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_bottom_nav);
    unbinder = ButterKnife.bind(this);
      if (Aesthetic.isFirstTime()) {
          Aesthetic.get()
                  .activityTheme(R.style.AppTheme)
                  .textColorPrimaryRes(R.color.text_color_primary)
                  .textColorSecondaryRes(R.color.text_color_secondary)
                  .colorPrimaryRes(R.color.md_green)
                  .colorAccentRes(R.color.md_blue)
                  .colorStatusBarAuto()
                  .colorNavigationBarAuto()
                  .textColorPrimary(Color.BLACK)
                  .navigationViewMode(NavigationViewMode.SELECTED_ACCENT)
                  .bottomNavigationBackgroundMode(BottomNavBgMode.BLACK_WHITE_AUTO)
                  .bottomNavigationIconTextMode(BottomNavIconTextMode.SELECTED_ACCENT)
                  .apply();
      }
    toolbar.setNavigationOnClickListener(
        new View.OnClickListener() {
          @Override
          public void onClick(View view) {
            finish();
          }
        });
  }
```
when i setup the sample app first time ,it crash and log is :
```java
07-03 03:01:27.949 11619-11619/? D/InflationInterceptor: Inflated -> com.afollestad.aestheticsample:id/bottom_tabs com.afollestad.aesthetic.AestheticBottomNavigationView
07-03 03:01:27.949 11619-11619/? W/System.err: java.lang.IllegalArgumentException: invalid value for field
07-03 03:01:27.949 11619-11619/? W/System.err:     at java.lang.reflect.Field.setField(Native Method)
07-03 03:01:27.949 11619-11619/? W/System.err:     at java.lang.reflect.Field.set(Field.java:588)
07-03 03:01:27.949 11619-11619/? W/System.err:     at com.afollestad.aesthetic.MaterialDialogsUtil.theme(MaterialDialogsUtil.java:82)
07-03 03:01:27.949 11619-11619/? W/System.err:     at com.afollestad.aesthetic.MaterialDialogsUtil$1.accept(MaterialDialogsUtil.java:117)
07-03 03:01:27.949 11619-11619/? W/System.err:     at com.afollestad.aesthetic.MaterialDialogsUtil$1.accept(MaterialDialogsUtil.java:112)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged$DistinctUntilChangedObserver.onNext(ObservableDistinctUntilChanged.java:85)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.drain(ObservableCombineLatest.java:246)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.combine(ObservableCombineLatest.java:199)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableCombineLatest$CombinerObserver.onNext(ObservableCombineLatest.java:316)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:64)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.drain(ObservableConcatMap.java:462)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver.onSubscribe(ObservableConcatMap.java:325)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableFromArray.subscribeActual(ObservableFromArray.java:30)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:54)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
07-03 03:01:27.949 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableCombineLatest$LatestCoordinator.subscribe(ObservableCombineLatest.java:119)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableCombineLatest.subscribeActual(ObservableCombineLatest.java:73)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.internal.operators.observable.ObservableDistinctUntilChanged.subscribeActual(ObservableDistinctUntilChanged.java:35)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10842)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10828)
07-03 03:01:27.959 11619-11619/? W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:10731)
07-03 03:01:27.959 11619-11619/? W/System.err:     at com.afollestad.aesthetic.MaterialDialogsUtil.observe(MaterialDialogsUtil.java:111)
07-03 03:01:27.959 11619-11619/? W/System.err:     at com.afollestad.aesthetic.Aesthetic.resume(Aesthetic.java:257)
07-03 03:01:27.959 11619-11619/? W/System.err:     at com.afollestad.aesthetic.AestheticActivity.onResume(AestheticActivity.java:19)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.Activity.performResume(Activity.java:5082)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2565)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2603)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2089)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3512)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread.access$700(ActivityThread.java:130)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.os.Looper.loop(Looper.java:137)
07-03 03:01:27.959 11619-11619/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:4745)
07-03 03:01:27.959 11619-11619/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
07-03 03:01:27.959 11619-11619/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
07-03 03:01:27.959 11619-11619/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
07-03 03:01:27.959 11619-11619/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
07-03 03:01:27.959 11619-11619/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
07-03 03:01:27.959 11619-11619/? D/AndroidRuntime: Shutting down VM
07-03 03:01:27.959 11619-11619/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa66cb228)
07-03 03:01:27.959 11619-11619/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NullPointerException
                                                       at com.afollestad.aesthetic.AestheticBottomNavigationView.onDetachedFromWindow(AestheticBottomNavigationView.java:170)
                                                       at android.view.View.dispatchDetachedFromWindow(View.java:11789)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2534)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
                                                       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2532)
                                                       at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2613)
                                                       at android.view.ViewRootImpl.doDie(ViewRootImpl.java:3962)
                                                       at android.view.ViewRootImpl.die(ViewRootImpl.java:3945)
                                                       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:375)
                                                       at android.view.WindowManagerImpl$CompatModeWrapper.removeViewImmediate(WindowManagerImpl.java:170)
                                                       at android.app.ActivityThread.cleanUpPendingRemoveWindows(ActivityThread.java:2587)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2651)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2089)
                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3512)
                                                       at android.app.ActivityThread.access$700(ActivityThread.java:130)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                       at dalvik.system.NativeStart.main(Native Method)
07-03 03:01:27.959 1453-10279/system_process W/ActivityManager:   Force finishing activity com.afollestad.aestheticsample/.BottomNavActivity
07-03 03:01:28.489 1453-1466/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{a7593040 com.afollestad.aestheticsample/.BottomNavActivity}
```
and when open the app second time the bottomNavigationView is black and white and no accent color on it like this(since my accent color is md_blue).
![image](https://user-images.githubusercontent.com/10767193/27776780-1052d3c8-5fe0-11e7-8384-8f2227370930.png)

is there something i did wrong?  
 thanks for any help :)

**Comment by boswelja** [comment]
You've done everything right I think, I'll just look into the source a bit

**Comment by boswelja** [comment]
@HIjack2015  Why did you modify the sample, if I may ask?

**Comment by HIjack2015** [comment]
@boswelja  because i'm developing a app. and  i want  to make BottomNavActivity as the launcher activity.
:)

**Comment by boswelja** [comment]
So why don't you just make your own bottom nav? If the issue persists after making your own BottomNav, I will look into it more

**Comment by boswelja** [comment]
For now, I can only pin it on the sample having issues as I cannot see any other problem.
