### ISSUE TITLE
Collapsing appbar causes crash

### ISSUE THREAD

**Issue by AkshayPathak** [afollestad/aesthetic#56]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

Tested on:
 - Aesthetic version: `0.4.7`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `HTC`
 - Device Name: `HTC One M8`

and,
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel`

and,
 - Device OS version: `7.0.0`
 - Device Manufacturer: `Samsung`
 - Device Name: `S7 Edge`

###### Stacktrace
```
Process: com.afollestad.aestheticsample, PID: 24841
java.lang.NullPointerException: source1 is null 
at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39) 
at io.reactivex.Observable.combineLatest(Observable.java:373)
at com.afollestad.aesthetic.AestheticCoordinatorLayout.onAttachedToWindow(AestheticCoordinatorLayout.java:130)
 at android.view.View.dispatchAttachedToWindow(View.java:15509)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2916)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
 at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2923)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1526)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
 at android.view.Choreographer.doCallbacks(Choreographer.java:686)
 at android.view.Choreographer.doFrame(Choreographer.java:621)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6119)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
 
###### Reproduction Steps
In the sample app, go to the `OTHER` tab and click `COLLAPSING APP BAR`. 

###### Expected Result
The collapsing app bar layout should open.

###### Actual Result
The app crashes.

**Comment by AkshayPathak** [comment]
This is similar to issue #3 but I am not sure how to fix it.

**Comment by PDDStudio** [comment]
I can confirm this. Same happens to me. Is there any fix/workaround for this?
