### ISSUE TITLE
i want to ignore my custom imageview, but Glide throws Exception

### ISSUE THREAD

**Issue by iota9star** [afollestad/aesthetic#67]
i am sorry my poor english.
i know glide don`t set tag to image view, what should i do?

```
   java.lang.IllegalArgumentException: You must not call setTag() on a view Glide is targeting
                                                                       at com.bumptech.glide.request.target.ViewTarget.getRequest(ViewTarget.java:133)
                                                                       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:367)
                                                                       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:432)
```

**Comment by boswelja** [comment]
Set the tag either before Glide starts loading the image, or wait until it's finished

**Comment by iota9star** [comment]
thanks ,  i made my custom image view extends aes image view and solved the problem

**Comment by boswelja** [comment]
can you close this issue then?

**Comment by iota9star** [comment]
if i use mikepenz`s [MaterialDrawer](https://github.com/mikepenz/MaterialDrawer) ,what should i do ?  it throws exception not found resource id, it can`t set tag
