### ISSUE TITLE
Crash in Util.resolveColor with null Context

### ISSUE THREAD

**Issue by shahidshaikhs** [afollestad/aesthetic#77]
Not really sure as to why is this happening. I could not replicate this on my end, but there were many crashing instances on random device. 
SDK version : 27 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
       at com.afollestad.aesthetic.Util.resolveColor(Util.java:85)
       at com.afollestad.aesthetic.Util.resolveColor(Util.java:80)
       at com.afollestad.aesthetic.Aesthetic.textColorSecondary(Aesthetic.java:435)
       at com.afollestad.aesthetic.AestheticTextView.onAttachedToWindow(AestheticTextView.java:44)
       at android.view.View.dispatchAttachedToWindow(View.java:17445)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1668)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
       at android.view.Choreographer.doCallbacks(Choreographer.java:723)
       at android.view.Choreographer.doFrame(Choreographer.java:658)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:442)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by hedongfu** [comment]
Why this bug closed without fix? My app has same issue and waiting for fix for long time.
Scenario:
1. Start app loading in vertical.
2. Rotate phone to Horizontal.
3. Press back button to exit.
Then I have this null exception with menu.
It seems when app start up, menu initialized in vertical mode. But If screen change to horizontal and I configured the activity without recreation. Then menu is not recreated. It has problem with aesthetic when app exiting.
Could you tell me how to fix it? 
Thank you.

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.5.0
