### ISSUE TITLE
CompositeDisposable.clear()' on a null object reference when the first started 

### ISSUE THREAD

**Issue by CcSimple** [afollestad/aesthetic#82]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.4.7`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `MI`
 - Device Name: `NOTE3`

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
-----The base
public abstract class BaseAestheticActivity extends AestheticActivity{
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(setLayoutResID());
        ButterKnife.bind(this);
        init(savedInstanceState);
    }
.........
}
-----The main
public class MainActivity extends BaseAestheticActivity implements ColorChooserDialog.ColorCallback,  {
    @Override
    protected int setLayoutResID() {
        return R.layout.activity_main;
    }
    @Override
    protected void init(@Nullable Bundle savedInstanceState) {
        if (Aesthetic.isFirstTime()) {
            Aesthetic.get()
                    .activityTheme(R.style.AppTheme)
                    .textColorPrimaryRes(R.color.text_color_primary)
                    .textColorSecondaryRes(R.color.text_color_secondary)
                    .colorPrimaryRes(R.color.colorPrimary)
                    .colorAccentRes(R.color.colorAccent)
                    .colorStatusBarAuto()
                    .colorNavigationBarAuto()
                    .navigationViewMode(NavigationViewMode.SELECTED_ACCENT)
                    .tabLayoutBackgroundMode(TabLayoutBgMode.PRIMARY)
                    .tabLayoutIndicatorMode(TabLayoutIndicatorMode.ACCENT)
                    .bottomNavigationBackgroundMode(BottomNavBgMode.PRIMARY)
                    .bottomNavigationIconTextMode(BottomNavIconTextMode.SELECTED_ACCENT)
                    .apply();
        }
    }
.........
}
```
```gradle
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.reactivex.disposables.CompositeDisposable.clear()' on a null object reference
at com.afollestad.aesthetic.AestheticBottomNavigationView.onDetachedFromWindow(AestheticBottomNavigationView.java:171)
at android.view.View.dispatchDetachedFromWindow(View.java:14598)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3074)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3066)
at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3104)
at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5657)
at android.view.ViewRootImpl.die(ViewRootImpl.java:5634)
at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:403)
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:358)
at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:118)
at android.app.ActivityThread.cleanUpPendingRemoveWindows(ActivityThread.java:3205)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3272)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4194)
at android.app.ActivityThread.access$1200(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5615)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

```xml
        <android.support.design.widget.BottomNavigationView
            android:id="@+id/bottom_tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom"
            app:elevation="@dimen/dp2"
            app:menu="@menu/main_bottom" />
```

**Comment by afollestad** [comment]
Will go away in the upcoming release.

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.5.0
