### ISSUE TITLE
java.lang.NullPointerException - 'Context.getResources()' on null object, in InflationInterceptor

### ISSUE THREAD

**Issue by hedongfu** [afollestad/aesthetic#86]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue description title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.5.3`
 - Device OS version: `7.0`, problem also existing on other version
 - Device Manufacturer: `Samsung`, problem also existing on other phone
 - Device Name: `S6`, problem also existing on other phone

Also, **please wrap Java and Logcats with syntax highlighting:**

```gradle
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:383)
        at android.view.View.<init>(View.java:3700)
        at android.view.View.<init>(View.java:3797)
        at android.view.ViewGroup.<init>(ViewGroup.java:503)
        at android.widget.LinearLayout.<init>(LinearLayout.java:200)
        at android.widget.LinearLayout.<init>(LinearLayout.java:196)
        at android.widget.LinearLayout.<init>(LinearLayout.java:192)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
        at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.kt:185) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:482) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:4079) 
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:4151) 
        at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2154) 
        at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575) 
        at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466) 
        at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:94) 
        at com.*******.LoadingProgressDialog.<init>(LoadingProgressDialog.java:18) 

        at android.app.Activity.performCreate(Activity.java:6178) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769) 
        at android.app.ActivityThread.access$900(ActivityThread.java:177) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5910) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200) 
```
 
###### Reproduction Steps
Just try to show dialog from an Activity.
This problem also existing if start an Activity with fragment. 

###### Expected Result
No crash

###### Actual Result
APP crash with "android.view.InflateException: Binary XML file line #24: Error inflating class <unknown>"

**Comment by TheAndroidMaster** [comment]
I believe I am encountering the same issue, happening on all of my emulators (tested every other sdk 19-27), and I believe that it is present all the way back to version 0.5.0, which does make me question if it is really an issue with aesthetic or if it's just me. If this is a problem on my part I greatly apologize, but I can't make heads or tails of the crash report other than it can't inflate a view because somewhere, somehow, the layout inflater is calling `getResources()` on a null context. 

That said, I did try removing aesthetic entirely from my project, and it works fine, so I can at least confirm that it is either an issue with aesthetic or my implementation of it. Source code I'm using is [here](https://github.com/TheAndroidMaster/Alarmio).

<details>
<summary>Crash log</summary>
<br>

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: james.alarmio, PID: 2326
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{james.alarmio/james.alarmio.activities.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                      at android.app.ActivityThread.access$800(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                      at android.view.LayoutInflater.createView(LayoutInflater.java:621)
                      at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.kt:185)
                      at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at james.alarmio.fragments.SplashFragment.onCreateView(SplashFragment.java:21)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2442)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                      at android.app.Activity.performStart(Activity.java:5241)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.constructNative(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:595)
                      at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.kt:185) 
                      at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at james.alarmio.fragments.SplashFragment.onCreateView(SplashFragment.java:21) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2442) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620) 
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171) 
                      at android.app.Activity.performStart(Activity.java:5241) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: java.lang.NullPointerException
                      at android.view.ViewConfiguration.get(ViewConfiguration.java:325)
                      at android.view.View.<init>(View.java:3448)
                      at android.view.View.<init>(View.java:3505)
                      at android.view.ViewGroup.<init>(ViewGroup.java:470)
                      at android.widget.FrameLayout.<init>(FrameLayout.java:101)
                      at android.widget.FrameLayout.<init>(FrameLayout.java:97)
                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:595) 
                      at com.afollestad.aesthetic.InflationInterceptor.onCreateView(InflationInterceptor.kt:185) 
                      at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at james.alarmio.fragments.SplashFragment.onCreateView(SplashFragment.java:21) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2442) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620) 
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171) 
                      at android.app.Activity.performStart(Activity.java:5241) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5017) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                      at dalvik.system.NativeStart.main(Native Method) 
```

</details>

**Comment by afollestad** [comment]
I believe this will mostly go away with current commits

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.6.0 should help
