### ISSUE TITLE
kotlin.KotlinNullPointerException Aesthetic.isDark

### ISSUE THREAD

**Issue by razar-dev** [afollestad/aesthetic#89]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of Aesthetic (see the README)
- [X] I have given my issue a description and title
- [X] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.5.3`
 - Device OS version: `4.4.2-8.1.0`
 - Device Manufacturer: `Other`
 - Device Name: `Other`

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
kotlin.KotlinNullPointerException
	at com.afollestad.aesthetic.Aesthetic.isDark(Aesthetic.kt:106)
	at com.afollestad.aesthetic.Aesthetic.colorCardViewBackground(Aesthetic.kt:464)
	at com.afollestad.aesthetic.AestheticCardView.onAttachedToWindow(AestheticCardView.kt:33)
	at android.view.View.dispatchAttachedToWindow(View.java:17400)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3321)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4959)
	at android.view.ViewGroup.addView(ViewGroup.java:4750)
	at android.view.ViewGroup.addView(ViewGroup.java:4690)
	at android.support.v7.widget.RecyclerView$5.addView(RecyclerView.java:851)
	at android.support.v7.widget.ChildHelper.addView(ChildHelper.java:107)
	at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8336)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8294)
	at android.support.v7.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8282)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1571)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1877)
	at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:407)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
	at android.view.Choreographer.doCallbacks(Choreographer.java:838)
	at android.view.Choreographer.doFrame(Choreographer.java:766)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6696)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

 
###### Reproduction Steps
The error occurs very rarely, and in different places

AppMetrica
	7.0	android	18,80%
 	8.0.0	android	18,80%
 	5.1.1	android	12,50%
 	6.0	android	12,50%
 	7.1.2	android	12,50%
 	4.4.2	android	6,25%
 	4.4.4	android	6,25%
 	6.0.1	android	6,25%
 	8.1.0	android	6,25%

**Comment by afollestad** [comment]
That'd happen if you access `isDark` before attaching Aesthetic to an Activity

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.6.0
