### ISSUE TITLE
NullPointerException when ProgressDialog show

### ISSUE THREAD

**Issue by hedongfu** [afollestad/aesthetic#93]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of Aesthetic (see the README)
- [ ] I have given my issue a description and title
- [ ] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.6.0.x`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `P8`

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
private ProgressDialog mProgressDialog;
mProgressDialog = new ProgressDialog(RingdroidEditActivity.this);
        mProgressDialog.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);
        mProgressDialog.setTitle(R.string.progress_dialog_loading);
        mProgressDialog.setCancelable(true);
        mProgressDialog
                .setOnCancelListener(new DialogInterface.OnCancelListener() {
                    public void onCancel(DialogInterface dialog) {
                        mLoadingKeepGoing = false;
                    }
                });
        mProgressDialog.show();
```

```gradle
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:365)
        at android.view.View.<init>(View.java:4019)
        at android.view.View.<init>(View.java:4137)
        at android.view.ViewGroup.<init>(ViewGroup.java:578)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:248)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:244)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:240)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:656) 
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:231) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at android.app.ProgressDialog.onCreate(ProgressDialog.java:160) 
        at android.app.Dialog.dispatchOnCreate(Dialog.java:524) 
        at android.app.Dialog.show(Dialog.java:385) 
        ********************************************
        at android.app.Activity.performCreate(Activity.java:6915) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
```

```xml
```
 
###### Reproduction Steps
mProgressDialog.show();

###### Expected Result
Dialog show normally

###### Actual Result
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method

**Comment by afollestad** [comment]
0.6.1 should make the problem a bit more clear, but won't fix it. https://github.com/afollestad/aesthetic/releases/tag/0.6.1

**Comment by hedongfu** [comment]
This is the new log with version 0.6.1, it seems the problem is "Caused by: java.lang.IllegalStateException: Unable to delegate inflation of RelativeLayout to normal LayoutInflater."

 --------- beginning of crash
09-11 19:31:50.938 20063-20063/****.****.**** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ****.****.****, PID: 20063
    java.lang.RuntimeException: Unable to start activity ComponentInfo{****.****.****/****.****.****.****}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class RelativeLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class RelativeLayout
     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class RelativeLayout
     Caused by: java.lang.IllegalStateException: Unable to delegate inflation of RelativeLayout to normal LayoutInflater.
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:262)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.app.ProgressDialog.onCreate(ProgressDialog.java:160)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:524)
        at android.app.Dialog.show(Dialog.java:385)
        at ****.****.****.****.loadFromFile(****.java:1145)
        at ****.****.****.****.refreshListView(****.java:445)
        at ****.****.****.****.onCreate(****.java:383)
        at android.app.Activity.performCreate(Activity.java:6915)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at com.afollestad.aesthetic.internal.InflationInterceptor.onCreateView(InflationInterceptor.kt:256)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.app.ProgressDialog.onCreate(ProgressDialog.java:160)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:524)
        at android.app.Dialog.show(Dialog.java:385)
09-11 19:31:50.940 20063-20063/****.****.**** E/AndroidRuntime:     at ****.****.****.****.loadFromFile(****.java:1145)
        at ****.****.****.****.refreshListView(****.java:445)
        at ****.****.****.****.onCreate(****.java:383)
        at android.app.Activity.performCreate(Activity.java:6915)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
        at android.view.ViewConfiguration.get(ViewConfiguration.java:365)
        at android.view.View.<init>(View.java:4019)
        at android.view.View.<init>(View.java:4137)
        at android.view.ViewGroup.<init>(ViewGroup.java:578)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:248)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:244)
        at android.widget.RelativeLayout.<init>(RelativeLayout.java:240)
        	... 27 more

**Comment by hedongfu** [comment]
I have several phones, this problem can only be reproduced on one Huawei phone.
I put ProgressBar in AlertDialog to replace ProgressDialog, there is still the crash problem.
I checked onCreateView of InflationInterceptor.kt, it seems there is no support for AlertDialog. Is that mean I can't use AlertDialog if aesthetic is in use?
Thanks.
