### ISSUE TITLE
KotlinNullPointerException after UI recreate in procedure onConfigurationChanged 

### ISSUE THREAD

**Issue by hedongfu** [afollestad/aesthetic#94]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Aesthetic (see the README)
- [x] I have given my issue a description and title
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Aesthetic version: `0.6.0`
 - Device OS version: `7.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `P8`

Also, **please wrap Java and Logcats with syntax highlighting:**

```java
public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

       // Inflate our UI from its XML layout description.
        setContentView(R.layout.mylayout);
}
```

```gradle
kotlin.KotlinNullPointerException
        at com.afollestad.aesthetic.Aesthetic.colorPrimary(Aesthetic.kt:169)
        at com.afollestad.aesthetic.Aesthetic.colorIconTitle(Aesthetic.kt:513)
        at com.afollestad.aesthetic.AestheticActionMenuItemView.setIcon(AestheticActionMenuItemView.kt:47)
        at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:126)
        at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:211)
        at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:188)
        at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:197)
        at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:105)
        at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:230)
        at android.support.v7.widget.ActionMenuView.onConfigurationChanged(ActionMenuView.java:131)
        at android.view.View.dispatchConfigurationChanged(View.java:13124)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1506)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1510)
        at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:4234)
        at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:5429)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1841)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

```xml
```
 
###### Reproduction Steps
Change phone's orientation from portrait to landscape, the UI will be recreate in procedure onConfigurationChanged. As I call setContentView to recreate the UI, then if leave in landscape mode, there is fatal error.

###### Expected Result
No fatal error.

###### Actual Result
kotlin.KotlinNullPointerException

**Comment by afollestad** [comment]
https://github.com/afollestad/aesthetic/releases/tag/0.6.1
